[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

# --- PHẦN BẮT BUỘC ĐỂ DÙNG SUPERVISORCTL ---
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
# -------------------------------------------

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:reverb]
command=php artisan reverb:start --host=0.0.0.0 --port=8080
directory=/var/www/html
autostart=true
autorestart=true
user=www-data
stderr_logfile=/var/log/reverb.err.log
stdout_logfile=/var/log/reverb.out.log
stopasgroup=true
killasgroup=true

[program:queue-worker]
command=php artisan queue:work database --sleep=3 --tries=3 --max-time=3600
directory=/var/www/html
autostart=true
autorestart=true
user=www-data
stderr_logfile=/var/log/queue.err.log
stdout_logfile=/var/log/queue.out.log
stopasgroup=true
killasgroup=true